services:
    db:
        image: postgres
        container_name: tchain_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - tchain_db:/var/lib/postgresql/data
    express-app:
        depends_on:
            - db
        build: 
            context: ./back
            dockerfile: Dockerfile
        ports: 
            - "3333:3333"
        restart: unless-stopped
        environment:
            - PORT=3333
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=tchain_db
            - DB_HOST=db
            - DB_PORT=5432
            - TOKEN_SECRET=secret
    next-app:
        depends_on:
            - express-app
        build: 
            context: ./front
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        restart: unless-stopped
        environment:
            - NEXT_PUBLIC_HOST=express-app
            - NEXT_PUBLIC_PORT=3333
volumes:
    tchain_db:
    pgadmin-data:


